
IMAGE_BASE_NAME=elements-docker-compose

# Note assumes container names generated by docker compose running in this directory

alias b-cli="docker exec docker-compose-bitcoind bitcoin-cli"
alias e1-cli="docker exec docker-compose-elementsd-1 elements-cli"
alias e2-cli="docker exec docker-compose-elementsd-2 elements-cli"
