
IMAGE_BASE_NAME=elements-docker-compose

# Note assumes container names generated by docker-compose running in this directory

alias b-cli="docker exec ${IMAGE_BASE_NAME}_bitcoind_1 bitcoin-cli"
alias e1-cli="docker exec ${IMAGE_BASE_NAME}_elementsd-1_1 elements-cli"
alias e2-cli="docker exec ${IMAGE_BASE_NAME}_elementsd-2_1 elements-cli"
